export const ACCIONES_AUDITORIA = {
  CREAR: 'crear',
  EDITAR: 'editar',
  ACTIVAR: 'activar',
  INACTIVAR: 'inactivar',
  CAMBIAR_ROL: 'cambiar_rol',
  ACCESO_DENEGADO: 'acceso_denegado',
   RESTABLECER_PASSWORD: 'restablecer_password',
} as const;

export type AccionAuditoria = (typeof ACCIONES_AUDITORIA)[keyof typeof ACCIONES_AUDITORIA];

export const ACCIONES_AUDITORIA_VALORES = [
  ACCIONES_AUDITORIA.CREAR,
  ACCIONES_AUDITORIA.EDITAR,
  ACCIONES_AUDITORIA.ACTIVAR,
  ACCIONES_AUDITORIA.INACTIVAR,
  ACCIONES_AUDITORIA.CAMBIAR_ROL,
  ACCIONES_AUDITORIA.ACCESO_DENEGADO,
  ACCIONES_AUDITORIA.RESTABLECER_PASSWORD,
  
] as const;

export const ENTIDADES_AUDITORIA = {
  SUCURSALES: 'sucursales',
  USUARIOS: 'usuarios',
  CATEGORIAS: 'categorias',
  PROVEEDORES: 'proveedores',
  CLIENTES: 'clientes',
  ACCESO: 'acceso',
} as const;

export type EntidadAuditoria = (typeof ENTIDADES_AUDITORIA)[keyof typeof ENTIDADES_AUDITORIA];

export const ENTIDADES_AUDITORIA_VALORES = [
  ENTIDADES_AUDITORIA.SUCURSALES,
  ENTIDADES_AUDITORIA.USUARIOS,
  ENTIDADES_AUDITORIA.CATEGORIAS,
  ENTIDADES_AUDITORIA.PROVEEDORES,
  ENTIDADES_AUDITORIA.CLIENTES,
  ENTIDADES_AUDITORIA.ACCESO,
] as const;
